# Appium Server Configuration
appiumServerURL=http://127.0.0.1:4723
nodePath=/opt/homebrew/bin/node
appiumJsPath=/usr/local/lib/node_modules/appium/build/lib/main.js
#############################
# Framework
#############################
platform=Android
appSource=LOCAL
htmlPage=https://cdi-deffered-link-2.pagedrop.io/
# Android
#############################
android.deviceName=samsung SM-M136B
android.platformVersion=14
android.platformName=Android
android.automationName=UiAutomator2
android.appPackage=religious.connect.app
android.appActivity=religious.connect.app.MainActivity
android.appPath=apps/Chottullink Deferred Test.apk
android.storePackage=com.android.vending
#############################
# iOS
#############################
ios.deviceName=iPhone 16
ios.platformVersion=17.5
ios.platformName=iOS
ios.automationName=XCUITest
ios.bundleId=com.atrangii.app
ios.appPath=apps/Atrangii_PROD.ipa
ios.storeBundleId=com.apple.AppStore
#############################
# Waits
#############################
implicitWait=20
explicitWait=30
#############################
#expected uRLS
#############################
expectedDeferredLink=https://www.connectingdotsinfotech.com?test=cdi&utm_source=appium&utm_medium=attributed%3Fappium&utm_campaign=announcing-funding-round-jul2026&utm_term=java%2Bappium%2Bselenium%F0%9D%97%A6&utm_content=javascript%3Fselenium%2Bappium
expectedShortLink=appiumtest.chottu.link/test1
expectedClickedUrl=https://appiumtest.chottu.link/test1
expectedStatus=Success
#############################
#server
#############################
execution=local
aws.appium.url=http://127.0.0.1:4723/wd/hub